### ISSUE TITLE
Feature request: Curve for each bar in stacked chart

### ISSUE THREAD

**Issue by jitsk** [bharadhwajcn/fubar-charts#1]
Type: Feature Request

Currently only the top edge in stack bar is curved when curve is set. It is useful to curve each bar in a stack. 
Example:
![tojithin](https://user-images.githubusercontent.com/19944203/27318964-a8c5dcc4-55ac-11e7-9a22-ae1d271795e9.png)

**Comment by bharadhwajcn** [comment]
@jitsk Added the feature. Please check the documentation to know, how to implement feature.
